import React from "react"
import type { NextPage } from "next"
import Head from "next/head"
import MainLayout from "../components/layouts/main/MainLayout"
import ProfileCard from "../components/home/ProfileCard"
import PostList from "../components/home/PostList"
import CategoryList from "../components/home/CategoryList"

const Categories: NextPage = () => {
    return (
        <React.Fragment>
            <Head>
                <title>Blokita. | Categories</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <MainLayout>
                <div className="w-full px-3">
                    <div className="max-w-[1400px] mx-auto py-12 grid grid-cols-1 xl:grid-cols-6 gap-6">
                        <CategoryList />
                        <ProfileCard />
                    </div>
                </div>
            </MainLayout>
        </React.Fragment>
    )
}

export default Categories
