import React from "react"
import type { NextPage } from "next"
import Head from "next/head"
import Hello from "../components/Hello"
import Navbar from "../components/Navbar"

const Home: NextPage = () => {
    return (
        <React.Fragment>
            <Head>
                <title>Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main data-theme="mytheme">
                <Navbar />
                <div className="w-full px-3">
                    <div className="max-w-[1400px] mx-auto">
                        <h1>content</h1>
                    </div>
                </div>
            </main>
        </React.Fragment>
    )
}

export default Home
